[general]
framerate = 60
autosens = 1
sensitivity = 120
overshoot = 20

[output]
method = ncurses
channels = stereo

[color]
gradient = 1
gradient_color_1 = '#cba6f7'
gradient_color_2 = '#8b5cf6'
gradient_color_3 = '#7c3aed'
gradient_color_4 = '#a78bfa'
gradient_color_5 = '#d8b4fe'
gradient_color_6 = '#f0abfc'
foreground = '#cba6f7'

[smoothing]
integral = 80
monstercat = 1
noise_reduction = 0.7